name = "billing-app"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"

compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
HOST_PROD = "http://78.14.5.157"

[observability.logs]
enabled = true
invocation_logs = true
