import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "@/components/theme-provider";
import { Providers } from "./providers";
import Head from "next/head";
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  navbar,
}: Readonly<{
  children: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <Head>
        <meta charSet="utf-8" />
      </Head>      
      
      <body className="min-h-screen bg-background text-foreground">
        <Providers>
          <ThemeProvider>
            <div className="flex min-h-screen flex-col">
              <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
                {navbar}
              </header>

              <div className="flex-1">
                {children}
              </div>
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
} 