import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "@/components/theme-provider";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  navbar,
}: Readonly<{
  children: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Forzamos al body a medir exactamente el alto de la pantalla sin scroll general */}
      <body className="w-full flex flex-col bg-background text-foreground h-full">
        <Providers>
          <ThemeProvider>
            
            {/* Contenedor del Navbar: flex-none evita que el sidebar lo colapse */}
            <header className="w-full flex-none z-50 border-b p-2">
              {navbar}
            </header>
            
            {/* Contenedor del contenido: aquí entra tu dashboard layout */}
            <div className="flex-1 w-full min-h-0 relative h-full">
              {children}
            </div>

          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
} 