export const REGIMENES_FISCALES  = [
  { value: "601", name: "601 - General de Ley Personas Morales" },
  { value: "603", name: "603 - Personas Morales con Fines no Lucrativos" },
  { value: "605", name: "605 - Sueldos y Salarios e Ingresos Asimilados a Salarios" },
  { value: "606", name: "606 - Arrendamiento" },
  { value: "608", name: "608 - Demás ingresos" },
  { value: "609", name: "609 - Consolidación" },
  { value: "610", name: "610 - Residentes en el Extranjero sin Establecimiento Permanente en México" },
  { value: "611", name: "611 - Ingresos por Dividendos (socios y accionistas)" },
  { value: "612", name: "612 - Personas Físicas con Actividades Empresariales y Profesionales" },
  { value: "614", name: "614 - Ingresos por intereses" },
  { value: "616", name: "616 - Sin obligaciones fiscales" },
  { value: "620", name: "620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos" },
  { value: "621", name: "621 - Incorporación Fiscal" },
  { value: "622", name: "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras" },
  { value: "623", name: "623 - Opcional para Grupos de Sociedades" },
  { value: "624", name: "624 - Coordinados" },
  { value: "628", name: "628 - Hidrocarburos" },
  { value: "607", name: "607 - Régimen de Enajenación o Adquisición de Bienes" },
  { value: "629", name: "629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales" },
  { value: "630", name: "630 - Enajenación de acciones en bolsa de valores" },
  { value: "615", name: "615 - Régimen de los ingresos por obtención de premios" },
  { value: "625", name: "625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas" },
  { value: "626", name: "626 - Régimen Simplificado de Confianza" }
];